export const CONFIG = {
    "mainMessage": [
        "───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
        "───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
        "                                                           bbbbbbb                                                                                 ",
        "WWWWWWWW                           WWWWWWWW                b:::::b                 OOOOOOOOO        SSSSSSSSSSSSSSS          jjjj                  ",
        "W::::::W                           W::::::W                b:::::b               OO:::::::::OO    SS:::::::::::::::S        j::::j                 ",
        "W::::::W                           W::::::W                b:::::b             OO:::::::::::::OO S:::::SSSSSS::::::S         jjjj                  ",
        "W::::::W                           W::::::W                b:::::b            O:::::::OOO:::::::OS:::::S     SSSSSSS                               ",
        " W:::::W           WWWWW           W:::::W eeeeeeeeeeee    b:::::bbbbbbbbb    O::::::O   O::::::OS:::::S                   jjjjjjj    ssssssssss   ",
        "  W:::::W         W:::::W         W:::::Wee::::::::::::ee  b::::::::::::::bb  O:::::O     O:::::OS:::::S                   j:::::j  ss::::::::::s  ",
        "   W:::::W       W:::::::W       W:::::We::::::eeeee:::::eeb::::::::::::::::b O:::::O     O:::::O S::::SSSS                 j::::jss:::::::::::::s ",
        "    W:::::W     W:::::::::W     W:::::We::::::e     e:::::eb:::::bbbbb:::::::bO:::::O     O:::::O  SS::::::SSSSS            j::::js::::::ssss:::::s",
        "     W:::::W   W:::::W:::::W   W:::::W e:::::::eeeee::::::eb:::::b    b::::::bO:::::O     O:::::O    SSS::::::::SS          j::::j s:::::s  ssssss ",
        "      W:::::W W:::::W W:::::W W:::::W  e:::::::::::::::::e b:::::b     b:::::bO:::::O     O:::::O       SSSSSS::::S         j::::j   s::::::s      ",
        "       W:::::W:::::W   W:::::W:::::W   e::::::eeeeeeeeeee  b:::::b     b:::::bO:::::O     O:::::O            S:::::S        j::::j      s::::::s   ",
        "        W:::::::::W     W:::::::::W    e:::::::e           b:::::b     b:::::bO::::::O   O::::::O            S:::::S        j::::jssssss   s:::::s ",
        "         W:::::::W       W:::::::W     e::::::::e          b:::::bbbbbb::::::bO:::::::OOO:::::::OSSSSSSS     S:::::S        j::::js:::::ssss::::::s",
        "          W:::::W         W:::::W       e::::::::eeeeeeee  b::::::::::::::::b  OO:::::::::::::OO S::::::SSSSSS:::::S ...... j::::js::::::::::::::s ",
        "           W:::W           W:::W         ee:::::::::::::e  b:::::::::::::::b     OO:::::::::OO   S:::::::::::::::SS  ...... j::::j s:::::::::::ss  ",
        "            WWW             WWW            eeeeeeeeeeeeee  bbbbbbbbbbbbbbbb        OOOOOOOOO      SSSSSSSSSSSSSSS    ...... j::::j  sssssssssss    ",
        "                                                                                                                            j::::j                 ",
        "                                                                                                                  jjjj      j::::j                 ",
        "                                                                                                                 j::::jj   j:::::j                 ",
        "                                                                                                                 j::::::jjj::::::j                 ",
        "                                                                                                                  jj::::::::::::j                  ",
        "                                                                                                                    jjj::::::jjj                   ",
        "                                                                                                                       jjjjjj                      ",
        "───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
        "───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
        "        │                                    │                                                 │                                                   ",
        "        └─> Made With <3 By <a href=\"https://deitsuki.netlify.app\">DeiTsuki</a>.        └─> Type 'help' to see available commands.        └─> Type 'cls' to clear the screen.",
        ""
    ],
    "mainMessageColor": "purpleblue"
}